from __future__ import annotations

from collections.abc import Iterator, Sequence
from contextlib import AbstractContextManager
from typing import Protocol

from ..domain.models import Incident, MetricPoint, Monitor, OutboxMessage


class Database(Protocol):
    def atomic(self) -> AbstractContextManager[None]: ...

    def add_monitor(self, monitor: Monitor) -> None: ...
    def save_monitor(self, monitor: Monitor) -> None: ...
    def get_monitor(self, org_id: str, monitor_id: str) -> Monitor | None: ...
    def find_monitor_by_name(self, org_id: str, name: str) -> Monitor | None: ...
    def list_monitors(self, org_id: str) -> Sequence[Monitor]: ...
    def list_monitors_for_metric(self, org_id: str, metric: str) -> Sequence[Monitor]: ...

    def append_points(self, points: Sequence[MetricPoint]) -> None: ...
    def recent_points(self, org_id: str, metric: str, limit: int) -> Sequence[MetricPoint]: ...

    def add_incident(self, incident: Incident) -> None: ...
    def save_incident(self, incident: Incident) -> None: ...
    def get_incident(self, org_id: str, incident_id: str) -> Incident | None: ...
    def find_unresolved_incident(self, org_id: str, monitor_id: str) -> Incident | None: ...
    def list_incidents(self, org_id: str) -> Sequence[Incident]: ...

    def add_outbox_message(self, message: OutboxMessage) -> None: ...
    def pending_outbox_messages(self, limit: int) -> Sequence[OutboxMessage]: ...
    def save_outbox_message(self, message: OutboxMessage) -> None: ...

    def iter_all_incidents(self) -> Iterator[Incident]: ...

